name: event_mate
description: Connect through events, share the moments!

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.2
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  google_sign_in: ^6.1.4
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  shared_preferences: ^2.2.0
  get_it: ^7.6.0
  sembast: ^3.5.0+1
  http: ^1.1.0
  dartz: ^0.10.1
  path_provider: ^2.1.0
  path: ^1.8.3
  cached_network_image: ^3.3.1
  bloc_concurrency: ^0.2.2
  fluttertoast: ^8.2.2
  provider: ^6.0.5
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  image_picker: ^1.0.4
  rxdart: ^0.27.7
  kt_dart: ^1.1.0
  google_nav_bar: ^5.0.6

  # Custom EventMate Packages
  ripple_animation:
    git:
      url: https://github.com/Event-Mate/ripple_animation.git
      ref: 804558ad4842095249e40dac8224e0844a96206f
  google_maps_flutter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  lint: ^2.1.2

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/images/eventmate_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/languages/
    - assets/svg/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
